gradle.properties, src/main/kotlin/kotlinx/kover/KoverPlugin.kt
=> Fixed "Execution optimizations" warnings for jvmArgumentProviders

src/main/kotlin/kotlinx/kover/KoverPlugin.kt
=> Added filter for binary reports

README.md, src/main/kotlin/kotlinx/kover/engines/intellij/Versions.kt
=> Upgrade version of the IntelliJ Coverage Engine

README.md, src/main/kotlin/kotlinx/kover/KoverPlugin.kt, src/main/kotlin/kotlinx/kover/tasks/KoverCollectingTask.kt, src/main/kotlin/kotlinx/kover/tasks/KoverHtmlReportTask.kt
=> Removed implicit dependencies from koverCollectReports task

build.gradle.kts, src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/DefaultSettingsTest.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/core/BaseGradleScriptTest.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Runner.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Types.kt, src/functionalTest/templates/scripts/buildscripts/groovy/kjvm/root, src/functionalTest/templates/scripts/buildscripts/groovy/kmp/root, src/functionalTest/templates/scripts/buildscripts/kotlin/kjvm/root, src/functionalTest/templates/scripts/buildscripts/kotlin/kmp/root, src/functionalTest/templates/scripts/settings/settings.gradle, src/functionalTest/templates/scripts/settings/settings.gradle.kts, src/functionalTest/templates/sources/simple-single/main/kotlin/Sources.kt, src/functionalTest/templates/sources/simple-single/test/kotlin/TestClass.kt, src/main/kotlin/kotlinx/kover/adapters/api/CompilationPluginAdapter.kt
=> Integration tests core prototype

src/main/kotlin/kotlinx/kover/tasks/KoverAggregateTask.kt, src/main/kotlin/kotlinx/kover/tasks/KoverModuleTask.kt
=> Made tasks cache relocatable

src/main/kotlin/kotlinx/kover/KoverPlugin.kt, src/main/kotlin/kotlinx/kover/engines/intellij/IntellijAgent.kt, src/main/kotlin/kotlinx/kover/engines/jacoco/JacocoAgent.kt
=> Added support of parallel tests execution

build.gradle.kts
=> Excluded Kotlin stdlib transitive dependency

src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/ConfigurationCacheTests.kt, src/main/kotlin/kotlinx/kover/KoverPlugin.kt, src/main/kotlin/kotlinx/kover/adapters/PluginAdaptersFactory.kt, src/main/kotlin/kotlinx/kover/engines/commons/Reports.kt, src/main/kotlin/kotlinx/kover/engines/intellij/IntellijAgent.kt, src/main/kotlin/kotlinx/kover/engines/intellij/IntellijReports.kt, src/main/kotlin/kotlinx/kover/engines/jacoco/JacocoAgent.kt, src/main/kotlin/kotlinx/kover/tasks/KoverHtmlReport.kt, src/main/kotlin/kotlinx/kover/tasks/KoverMergedTask.kt, src/main/kotlin/kotlinx/kover/tasks/KoverProjectTask.kt, src/main/kotlin/kotlinx/kover/tasks/KoverVerification.kt, src/main/kotlin/kotlinx/kover/tasks/KoverXmlReport.kt
=> Added Gradle configuration cache support

README.md, gradle.properties, src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/MultiProjectTests.kt, src/main/kotlin/kotlinx/kover/KoverPlugin.kt, src/main/kotlin/kotlinx/kover/Providers.kt, src/main/kotlin/kotlinx/kover/api/KoverExtension.kt, src/main/kotlin/kotlinx/kover/engines/commons/Reports.kt, src/main/kotlin/kotlinx/kover/engines/intellij/IntellijReports.kt, src/main/kotlin/kotlinx/kover/engines/jacoco/JacocoReports.kt, src/main/kotlin/kotlinx/kover/tasks/KoverCollectingTask.kt, src/main/kotlin/kotlinx/kover/tasks/KoverHtmlReport.kt, src/main/kotlin/kotlinx/kover/tasks/KoverMergedTask.kt
=> Implemented the use of the full path to the project

src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/VerificationTests.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/utils/Commons.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Builder.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Runner.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Types.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Writer.kt, src/main/kotlin/kotlinx/kover/api/Rules.kt, src/main/kotlin/kotlinx/kover/engines/intellij/IntellijReports.kt, src/main/kotlin/kotlinx/kover/engines/intellij/IntellijVerification.kt, src/main/kotlin/kotlinx/kover/engines/intellij/Versions.kt, src/main/kotlin/kotlinx/kover/json/SimpleParser.kt, src/main/kotlin/kotlinx/kover/json/SimpleWriter.kt, src/main/kotlin/kotlinx/kover/tasks/KoverVerification.kt, src/test/kotlin/JsonTest.kt
additionally, introduced a simple json converter to avoid dependencies in the plugin on third-party libraries
=> Added support for the IntelliJ verifier

src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/utils/Defaults.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Runner.kt, src/main/kotlin/kotlinx/kover/api/CoverageEngines.kt, src/main/kotlin/kotlinx/kover/appliers/KoverTaskApplier.kt
Minor tweak that seems a little more clear to me :)
=> define test report extension in the report-vendor enum

README.md, src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/AnnotationFilterTests.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/framework/checker/Checker.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/framework/configurator/BuildConfigurator.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/framework/configurator/ConfigTypes.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/framework/configurator/ConfiguratorTypes.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/framework/runner/BuildRunner.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/framework/writer/KoverMergedWriter.kt, src/functionalTest/kotlin/kotlinx/kover/test/functional/framework/writer/KoverWriter.kt, src/functionalTest/templates/sources/annotations-main/main/kotlin/Sources.kt, src/functionalTest/templates/sources/annotations-main/test/kotlin/TestClass.kt, src/main/kotlin/kotlinx/kover/api/KoverConfig.kt, src/main/kotlin/kotlinx/kover/api/KoverConstants.kt, src/main/kotlin/kotlinx/kover/appliers/KoverMergedApplier.kt, src/main/kotlin/kotlinx/kover/appliers/KoverProjectApplier.kt, src/main/kotlin/kotlinx/kover/engines/commons/EngineManager.kt, src/main/kotlin/kotlinx/kover/engines/commons/Reports.kt, src/main/kotlin/kotlinx/kover/engines/intellij/IntellijReports.kt, src/main/kotlin/kotlinx/kover/engines/intellij/IntellijVerification.kt, src/main/kotlin/kotlinx/kover/engines/intellij/KoverAggregator.kt, src/main/kotlin/kotlinx/kover/engines/jacoco/JacocoReports.kt, src/main/kotlin/kotlinx/kover/tasks/KoverHtmlTask.kt, src/main/kotlin/kotlinx/kover/tasks/KoverReportTask.kt, src/main/kotlin/kotlinx/kover/tasks/KoverVerificationTask.kt, src/main/kotlin/kotlinx/kover/tasks/KoverXmlTask.kt
* added annotation filtering API
* added functional tests
* XML and HTML report generation moved to Kover Aggregator
* default and minimal IntelliJ (Kover) Engine upgraded to `1.0.682`
=> Implemented filtering of reports by annotation

README.md
As described here: https://github.com/Kotlin/kotlinx-kover/issues/248
So people can find the issue easier
=> Adds the error message one would get when instrumenation is not enabled

CONTRIBUTING.md, README.md
As promised, I went over documentation and here are my proposals. Sorry, got carried away a little bit.
DISCLAIMER: I'm neither a technical writer nor a native English speaker, but I do have some experience with English and reading good and bad documentation :) So take everything with a grain of salt, feel free to revert any changes you don't agree with and ask questions.
More importantly, I'm not a Kover expect by far, so please proofread everything :) I might've misunderstood some things.
Changes made throughout the whole file:
* Quickstart now truly offers a quick start - it was strange to see the tasks all the way in the back. As a developer, I just want to copy-paste the plugin and see which task I need to run. Done. If there's any problems, I'll come back and read the docs.
* Made …
=> Revise documentation

api/kover-gradle-plugin.api, build.gradle.kts, src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/ProjectApplier.kt, src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/ReportsApplier.kt, src/main/kotlin/kotlinx/kover/gradle/plugin/commons/Constants.kt, src/main/kotlin/kotlinx/kover/gradle/plugin/commons/Naming.kt, src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/Commons.kt, src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverProjectExtension.kt, src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverReportExtension.kt, src/main/kotlin/kotlinx/kover/gradle/plugin/util/json/SimpleWriter.kt
=> Added binary compatibility validator

docs/gradle-plugin/configuring.md
=> Updated documentation on filtering by annotations

api/kover-gradle-plugin.api, docs/gradle-plugin/configuring.md, docs/gradle-plugin/index.md, src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/CompilationFiltersTests.kt, src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/writer/KoverWriter.kt, src/functionalTest/templates/builds/sourcesets-mpp/build.gradle.kts, src/functionalTest/templates/builds/sourcesets-mpp/settings.gradle.kts, src/functionalTest/templates/builds/sourcesets-mpp/src/jvmExtra/kotlin/ExtraClass.kt, src/functionalTest/templates/builds/sourcesets-mpp/src/jvmMain/kotlin/AppClasses.kt, src/functionalTest/templates/builds/sourcesets-mpp/src/jvmTest/kotlin/TestClasses.kt, src/functionalTest/templates/builds/sourcesets/build.gradle.kts, src/functionalTest/templates/builds/sourcesets/settings.gradle.kts, src/functionalTest/templates/builds/sourcesets/src/extra/kotlin/ExtraClass.kt, src/functionalTest/templates/builds/sourcesets/src/main/kotlin/AppClasses.kt, src/functionalTest/templates/builds/sourcesets/src/test/kotlin/TestClasses.kt, src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverProjectExtension.kt, src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/internal/KoverProjectExtension.kt, src/main/kotlin/kotlinx/kover/gradle/plugin/locators/Commons.kt, src/main/kotlin/kotlinx/kover/gradle/plugin/locators/KotlinJvmLocator.kt, src/main/kotlin/kotlinx/kover/gradle/plugin/locators/KotlinMultiPlatformLocator.kt
=> Added a filter of source sets

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/AccessorsTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/MultiProjectTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/NoTestReportsTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/TaskFilteringTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/checker/Checker.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/runner/StepsRunner.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/starter/Commons.kt, kover-gradle-plugin/src/functionalTest/templates/builds/no-tests-jvm/build.gradle.kts, kover-gradle-plugin/src/functionalTest/templates/builds/no-tests-jvm/settings.gradle.kts, kover-gradle-plugin/src/functionalTest/templates/builds/no-tests-jvm/src/main/kotlin/ExampleClass.kt, kover-gradle-plugin/src/functionalTest/templates/builds/no-tests-mpp/build.gradle.kts, kover-gradle-plugin/src/functionalTest/templates/builds/no-tests-mpp/settings.gradle.kts, kover-gradle-plugin/src/functionalTest/templates/builds/no-tests-mpp/src/jvmMain/kotlin/ExampleClass.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/reports/ReportsVariantApplier.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/AbstractKoverReportTask.kt
=> Added ability to generate reports even if there are no tests in the project

kover-gradle-plugin/api/kover-gradle-plugin.api, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/AccessorsTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/LogTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/LoggingTaskTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/runner/GradleRunner.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/writer/KoverReportWriter.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/reports/ReportsVariantApplier.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/commons/Naming.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/commons/Paths.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverNames.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverReportExtension.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/internal/KoverReportExtension.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/KoverFormatCoverageTask.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/services/KoverPrintLogTask.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/CoverageTool.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/Verification.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/jacoco/Evaluation.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/jacoco/JacocoTool.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/jacoco/Verification.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/kover/Evaluation.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/kover/KoverTool.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/kover/Verification.kt
=> Added task to print coverage to logs

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/AdaptersTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/AndroidConfigsTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/CompilationFiltersTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/CountersValueTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/InstrumentationFilteringTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/MultiProjectTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/NoTestReportsTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ReportAnnotationFilterTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ReportsFilteringTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/VariantUsageTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/checker/Checker.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/checker/CheckerTypes.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/checker/Defaults.kt, kover-gradle-plugin/src/functionalTest/templates/builds/disabledUnitTests/app/build.gradle.kts, kover-gradle-plugin/src/functionalTest/templates/builds/disabledUnitTests/app/src/main/AndroidManifest.xml, kover-gradle-plugin/src/functionalTest/templates/builds/disabledUnitTests/app/src/main/java/kotlinx/kover/test/android/DebugUtil.kt, kover-gradle-plugin/src/functionalTest/templates/builds/disabledUnitTests/app/src/main/java/kotlinx/kover/test/android/MainActivity.kt, kover-gradle-plugin/src/functionalTest/templates/builds/disabledUnitTests/app/src/main/java/kotlinx/kover/test/android/Maths.kt, kover-gradle-plugin/src/functionalTest/templates/builds/disabledUnitTests/app/src/main/res/layout/activity_main.xml, kover-gradle-plugin/src/functionalTest/templates/builds/disabledUnitTests/app/src/main/res/values/colors.xml, kover-gradle-plugin/src/functionalTest/templates/builds/disabledUnitTests/app/src/main/res/values/strings.xml, kover-gradle-plugin/src/functionalTest/templates/builds/disabledUnitTests/app/src/main/res/values/themes.xml, kover-gradle-plugin/src/functionalTest/templates/builds/disabledUnitTests/app/src/test/java/kotlinx/kover/test/android/LocalTests.kt, kover-gradle-plugin/src/functionalTest/templates/builds/disabledUnitTests/build.gradle.kts, kover-gradle-plugin/src/functionalTest/templates/builds/disabledUnitTests/gradle.properties, kover-gradle-plugin/src/functionalTest/templates/builds/disabledUnitTests/settings.gradle.kts, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/locators/Android.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/locators/Jvm.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/locators/KotlinMultiPlatformLocator.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/util/DynamicBean.kt
Fixes #405
A small refactoring of DynamicBean was also carried out
=> Fixed lookup for tests if unit tests are disabled in Android config

docs/gradle-plugin/configuring.md, docs/gradle-plugin/index.md, kover-cli/src/main/kotlin/kotlinx/kover/cli/commands/ReportCommand.kt, kover-gradle-plugin/api/kover-gradle-plugin.api, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/AccessorsTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/BinaryReportTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/IcReportTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/VersionsInExamplesTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/configurator/ConfiguratorTypes.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/writer/KoverReportWriter.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/writer/Providers.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/reports/ReportsVariantApplier.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/commons/Naming.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/commons/Paths.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverNames.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverReportExtension.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/internal/KoverReportExtension.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/KoverBinaryTask.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/KoverIcTask.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/CoverageTool.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/jacoco/JacocoTool.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/kover/IcReport.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/kover/KoverHtmlOrXmlReport.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/kover/KoverTool.kt
=> Implemented task of generating binary report

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/BuildCacheRelocationTests.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/commons/Artifacts.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/AbstractKoverReportTask.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/services/KoverArtifactGenerationTask.kt
=> Replaced absolute paths in the Kover artifact with relative ones

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/GradleValidationTests.kt
=> Added functional test on Gradle nested classes validation error

kover-gradle-plugin/examples/android/dynamic/app/build.gradle.kts, kover-gradle-plugin/examples/android/dynamic/app/src/main/AndroidManifest.xml, kover-gradle-plugin/examples/android/dynamic/app/src/main/java/kotlinx/kover/test/android/DebugUtil.kt, kover-gradle-plugin/examples/android/dynamic/app/src/main/java/kotlinx/kover/test/android/MainActivity.kt, kover-gradle-plugin/examples/android/dynamic/app/src/main/java/kotlinx/kover/test/android/Maths.kt, kover-gradle-plugin/examples/android/dynamic/app/src/main/res/layout/activity_main.xml, kover-gradle-plugin/examples/android/dynamic/app/src/main/res/values/colors.xml, kover-gradle-plugin/examples/android/dynamic/app/src/main/res/values/strings.xml, kover-gradle-plugin/examples/android/dynamic/app/src/main/res/values/themes.xml, kover-gradle-plugin/examples/android/dynamic/app/src/test/java/kotlinx/kover/test/android/LocalTests.kt, kover-gradle-plugin/examples/android/dynamic/build.gradle.kts, kover-gradle-plugin/examples/android/dynamic/dyn/build.gradle.kts, kover-gradle-plugin/examples/android/dynamic/dyn/src/main/AndroidManifest.xml, kover-gradle-plugin/examples/android/dynamic/dyn/src/main/java/kotlinx/kover/test/android/dyn/DebugUtil.kt, kover-gradle-plugin/examples/android/dynamic/dyn/src/main/java/kotlinx/kover/test/android/dyn/MagicFactory.kt, kover-gradle-plugin/examples/android/dynamic/dyn/src/test/java/kotlinx/kover/test/android/LocalLibTests.kt, kover-gradle-plugin/examples/android/dynamic/gradle.properties, kover-gradle-plugin/examples/android/dynamic/settings.gradle.kts, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/DynamicFeatureTests.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/locators/CompilationsListeners.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/locators/KotlinAndroidLocator.kt
=> Added support for Android dynamic feature plugins

docs/gradle-plugin/configuring.md, kover-gradle-plugin/api/kover-gradle-plugin.api, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/XmlReportTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/writer/KoverReportWriter.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/reports/ReportsVariantApplier.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverReportExtension.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/internal/KoverReportExtension.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/KoverXmlTask.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/CoverageTool.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/jacoco/JacocoHtmlOrXmlReport.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/jacoco/JacocoTool.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/kover/KoverHtmlOrXmlReport.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/kover/KoverTool.kt
=> Added the ability to specify a header for an XML report

build-logic/src/main/kotlin/kotlinx/kover/conventions/kover-publishing-conventions.gradle.kts, gradle/libs.versions.toml, kover-gradle-plugin/build.gradle.kts, kover-offline-runtime/src/main/java/kotlinx/kover/offline/runtime/api/BranchCoverage.java, kover-offline-runtime/src/main/java/kotlinx/kover/offline/runtime/api/ClassCoverage.java, kover-offline-runtime/src/main/java/kotlinx/kover/offline/runtime/api/KoverRuntime.java, kover-offline-runtime/src/main/java/kotlinx/kover/offline/runtime/api/LineCoverage.java, kover-offline-runtime/src/main/java/kotlinx/kover/offline/runtime/api/MethodCoverage.java
Also fixed invalid javadocs
Resolves #66
=> Added support for the publishing plugin to Gradle Plugin Portal

gradle/libs.versions.toml, kover-features-jvm/src/main/java/kotlinx/kover/features/jvm/impl/Wildcards.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ConstantObjectTests.kt, kover-gradle-plugin/src/functionalTest/templates/builds/counters/src/main/kotlin/Objects.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverVersions.kt
=> Excluded from report companion objects with only constants

gradle/libs.versions.toml, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/CountersValueTests.kt, kover-gradle-plugin/src/functionalTest/templates/builds/k2-counters/build.gradle.kts, kover-gradle-plugin/src/functionalTest/templates/builds/k2-counters/settings.gradle.kts, kover-gradle-plugin/src/functionalTest/templates/builds/k2-counters/src/main/kotlin/Branches.kt, kover-gradle-plugin/src/functionalTest/templates/builds/k2-counters/src/test/kotlin/TestClass.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverVersions.kt
=> Fixed coverage evaluation for enum in K2

gradle/libs.versions.toml, kover-gradle-plugin/api/kover-gradle-plugin.api, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/CountersValueTests.kt, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/checker/Checker.kt, kover-gradle-plugin/src/functionalTest/templates/builds/counters/build.gradle.kts, kover-gradle-plugin/src/functionalTest/templates/builds/counters/src/main/java/TryFinally.java, kover-gradle-plugin/src/functionalTest/templates/builds/counters/src/main/java/TryWithResources.java, kover-gradle-plugin/src/functionalTest/templates/builds/counters/src/test/kotlin/TestClass.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverVersions.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/CoverageTool.kt
=> Added tests on try-finally and try-with-resources

build-logic/build.gradle.kts, build-logic/src/main/kotlin/kotlinx/kover/conventions/kover-publishing-conventions.gradle.kts, kover-cli/build.gradle.kts, kover-features-jvm/build.gradle.kts, kover-gradle-plugin/build.gradle.kts, kover-jvm-agent/build.gradle.kts, kover-maven-plugin/build.gradle.kts, kover-offline-runtime/build.gradle.kts, settings.gradle.kts
- https://blog.gradle.org/simpler-kotlin-dsl-property-assignment
- Enable Typesafe Project Accessors
=> Applied Simple Kotlin DSL Property Assignment

kover-gradle-plugin/api/kover-gradle-plugin.api, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/InstrumentationFilteringTests.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/KoverMerge.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/instrumentation/JvmTestTaskConfigurator.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverVariantConfig.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/internal/VariantsImpl.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/CoverageTool.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/jacoco/JacocoOnlineInstrumentation.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/jacoco/JacocoTool.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/kover/KoverOnlineInstrumentation.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/kover/KoverTool.kt
=> Implemented ability to specify instrumentation include filter

kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/commons/artifacts/KoverUsageAttr.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/project/KoverProjectGradlePlugin.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/KoverSettingsGradlePlugin.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/PrepareKover.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/artifacts/AbstractVariantArtifacts.kt
=> Added USAGE attribute to all Kover configurations

kover-gradle-plugin/api/kover-gradle-plugin.api, kover-gradle-plugin/docs/aggregated.md, kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/SettingsPluginTests.kt, kover-gradle-plugin/src/functionalTest/templates/builds/settings-plugin-verify/build.gradle.kts, kover-gradle-plugin/src/functionalTest/templates/builds/settings-plugin-verify/settings.gradle.kts, kover-gradle-plugin/src/functionalTest/templates/builds/settings-plugin-verify/src/main/kotlin/RootClass.kt, kover-gradle-plugin/src/functionalTest/templates/builds/settings-plugin-verify/src/test/kotlin/RootTest.kt, kover-gradle-plugin/src/functionalTest/templates/builds/settings-plugin-verify/subproject/build.gradle.kts, kover-gradle-plugin/src/functionalTest/templates/builds/settings-plugin-verify/subproject/src/main/kotlin/SubprojectClass.kt, kover-gradle-plugin/src/functionalTest/templates/builds/settings-plugin-verify/subproject/src/test/kotlin/ATest.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/KoverParametersProcessor.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/KoverSettingsGradlePlugin.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/dsl/KoverSettingsExtension.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/dsl/intern/KoverSettingsExtensionImpl.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/dsl/intern/ReportsSettingsImpl.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/dsl/intern/VerificationRuleSettingsImpl.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/dsl/intern/VerifySettingsImpl.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/tasks/AbstractKoverReportTask.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/tasks/AbstractKoverTask.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/tasks/CommonTypes.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/tasks/KoverHtmlReportTask.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/tasks/KoverVerifyTask.kt, kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/tasks/KoverXmlReportTask.kt
Added ability te specify coverage verification rules via settings or CLI
=> Implemented verification in Kover Aggregated Plugin
