Kotlin/kotlinx-kover

README.md

Simply by following the README caused this compilation error below, so I just made a tiny fix here.
```
* What went wrong:
Execution failed for task ':shared:testDebugUnitTest'.
> IntelliJ engine version 1.0.637 is too low, minimal version is 1.0.639
```
The error occurred in 
- skeleton sample KMM application project made by KMM plugin
- Android Studio Bumblebee | 2021.1.1 Beta 5
I made the value same as https://github.com/Kotlin/kotlinx-kover/blob/bedeb7a8785665d649560add625d67d81e55f60d/src/main/kotlin/kotlinx/kover/engines/intellij/Versions.kt#L7

Update README.md to update intelliJEngineVersion

---

README.md
src/main/kotlin/kotlinx/kover/KoverPlugin.kt
src/main/kotlin/kotlinx/kover/adapters/PluginAdaptersFactory.kt
src/main/kotlin/kotlinx/kover/api/KoverExtension.kt

Added property to exclude Android classes from the instrumentation

---

src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/AdaptersTests.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/core/BaseGradleScriptTest.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Loader.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Runner.kt
src/functionalTest/templates/projects/different-plugins/build.gradle.kts
src/functionalTest/templates/projects/different-plugins/settings.gradle.kts
src/functionalTest/templates/projects/different-plugins/submodule-multiplatform/build.gradle.kts
src/functionalTest/templates/projects/different-plugins/submodule-multiplatform/src/commonMain/kotlin/CommonClass.kt
src/functionalTest/templates/projects/different-plugins/submodule-multiplatform/src/commonTest/kotlin/CommonTest.kt
src/functionalTest/templates/projects/different-plugins/submodule-multiplatform/src/jvmMain/kotlin/JvmClass.kt
src/functionalTest/templates/projects/different-plugins/submodule-multiplatform/src/jvmTest/kotlin/JvmTest.kt
src/main/kotlin/kotlinx/kover/adapters/KotlinMultiplatformPluginAdapter.kt

Kotlin Multiplatform plugin adapter rewritten to use reflection

---

README.md

I was reading through the Kover documentation while using it, and noticed some small grammatical improvements that would make it easier to read in my opinion. Thanks so much for the work, I love the project!

Add some grammatical improvements to documentation in README

---

src/main/kotlin/kotlinx/kover/KoverPlugin.kt

Checking parent projects causes a deadlock when projects are deeply nested.
Fixes #116

Removed checking of parent projects for re-apply of the plugin

---

README.md
src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/AdaptersTests.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/InstrumentationFilteringTests.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/MultiProjectTests.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/utils/Commons.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/utils/Defaults.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Runner.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Types.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/core/writer/KoverExtensionWriter.kt
src/main/kotlin/kotlinx/kover/appliers/KoverTaskApplier.kt
src/main/kotlin/kotlinx/kover/engines/commons/AgentFilters.kt
src/main/kotlin/kotlinx/kover/engines/commons/EngineManager.kt
src/main/kotlin/kotlinx/kover/engines/intellij/IntellijAgent.kt
src/main/kotlin/kotlinx/kover/engines/jacoco/JacocoAgent.kt

Added instrumentation filtering by common filters

---

src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/VerificationTests.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Runner.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Types.kt
src/functionalTest/templates/sources/verification/main/kotlin/FirstClasses.kt
src/functionalTest/templates/sources/verification/main/kotlin/SecondClasses.kt
src/functionalTest/templates/sources/verification/test/kotlin/TestClass.kt
src/main/kotlin/kotlinx/kover/api/KoverConstants.kt
src/main/kotlin/kotlinx/kover/engines/commons/Reports.kt
src/main/kotlin/kotlinx/kover/engines/intellij/IntellijVerification.kt
src/main/kotlin/kotlinx/kover/engines/jacoco/JacocoReports.kt

- IntelliJ Engine version upgraded to 1.0.680
- added tests on verification error
Fixes #211, #210, #212

Fixed instrumentation counter in IntelliJ verifier

---

src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/TasksOrderingTests.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Builder.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/core/Types.kt
src/functionalTest/kotlin/kotlinx/kover/test/functional/core/writer/MergedExtensionWriter.kt
src/main/kotlin/kotlinx/kover/appliers/KoverMergedApplier.kt
src/main/kotlin/kotlinx/kover/appliers/KoverProjectApplier.kt

Ordered report tasks before verification

---

README.md
src/main/kotlin/kotlinx/kover/api/KoverConfig.kt

Updated docs for onCheck properties

---

src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/MultiProjectTests.kt
src/main/kotlin/kotlinx/kover/appliers/KoverMergedApplier.kt

filter out projects without a build file 

---

src/functionalTest/kotlin/kotlinx/kover/test/functional/cases/ReportsFilteringTests.kt
src/main/kotlin/kotlinx/kover/engines/commons/EngineManager.kt
src/main/kotlin/kotlinx/kover/engines/commons/Reports.kt
src/main/kotlin/kotlinx/kover/engines/jacoco/JacocoReports.kt

Added JaCoCo reports filtering

---

src/main/kotlin/kotlinx/kover/KoverPlugin.kt
src/main/kotlin/kotlinx/kover/api/KoverConstants.kt
src/main/kotlin/kotlinx/kover/util/Versions.kt

At the moment, when trying to use a plugin with a Gradle version less than the minimum, the user receives non-obvious errors.
In order to explicitly tell the user the reason, we need to add a check at the plugin.

Added Gradle minimum version check

---

src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ReportsFilteringTests.kt
src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/VerificationTests.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/ReportsApplier.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/tools/jacoco/Verification.kt

Fixes #366
The report mistakenly took into account only filters inside the report and common filters for all variants, in fact, the overriding order should be: common filters for all variants > filters per variant > filters for a specific report in the variant

Fixed variant level filters for reports

---

api/kover-gradle-plugin.api
src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/writer/KoverReportWriter.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/ReportsApplier.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverReportExtension.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverVersions.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/internal/KoverReportExtension.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/KoverHtmlTask.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/tools/CoverageTool.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/tools/jacoco/JacocoHtmlOrXmlReport.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/tools/jacoco/JacocoTool.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/tools/kover/KoverHtmlOrXmlReport.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/tools/kover/KoverTool.kt

As last step for [IDEA-169757: Code coverage report: html file encoding](https://youtrack.jetbrains.com/issue/IDEA-169757)  and https://github.com/JetBrains/coverage-report/pull/3,  https://github.com/JetBrains/intellij-coverage/pull/57, we need to modify interface to inject charset from configuration.
Reviews will be of great help to resolve issue i'm working on 😄 thanks, bro :)

IDEA-169757 : support charset for html report

---

CHANGELOG.md

- click migration guid at `CHANGELOG.md`
> Also same as `main` branch

Fix broken migration link in CHANGELOG.md

---

src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ReportsCachingTests.kt
src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/configurator/BuildConfigurator.kt
src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/configurator/ConfiguratorTypes.kt
src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/runner/BuildRunner.kt
src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/starter/Single.kt
src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/starter/Sliced.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/AbstractKoverReportTask.kt

In order to carry out up-to-date checks correctly, it is necessary to add the source directories and binary reports to Kover tasks inputs
Fixes #371

Fixed up-to-date checks for Kover tasks

---

src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ArtifactGenerationTests.kt
src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/AbstractKoverReportTask.kt

The task tree is built at the configuration stage, so getting artifacts from dependencies can lead to premature task launches, deadlocks, and performance degradation. 
To eliminate resolution, it was necessary to use the Provider obtained from the corresponding FileCollection.

Removed Kover artifact resolution during configuration time

---

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/AccessorsTests.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/BuildCacheRelocationTests.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ConfigurationCacheTests.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ConfigurationOrderTests.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/runner/BuildsRunner.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/runner/CustomizableRunning.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/starter/Commons.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/starter/Example.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/starter/Single.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/starter/Sliced.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/starter/Template.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/JvmTestTaskConfigurator.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/services/KoverAgentJarTask.kt

Using `PathSensitivity.ABSOLUTE` in all cases will lead to a cache miss
Fixes #413

Fixed issues with cache miss of build cache at the time of relocation

---

kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverReportExtension.kt

Whilst reading the Kdoc I noticed that the docs for the `KoverReportExtension.xml` was incorrectly documented as configuring `html` reports.
I've opened the PR, but haven't been through every step of the contribution guidelines. I will do it shortly.

Updates KDoc for `KoverReportExtension.xml` to be documented as `xml` configuring, not `html`

---

kover-gradle-plugin/build.gradle.kts
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/MetadataCompatibilityTests.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/common/Environment.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/runner/BuildsRunner.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/runner/CustomizableRunning.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/starter/Commons.kt
kover-gradle-plugin/src/functionalTest/templates/builds/buildsrc-usage/build.gradle.kts
kover-gradle-plugin/src/functionalTest/templates/builds/buildsrc-usage/buildSrc/build.gradle.kts
kover-gradle-plugin/src/functionalTest/templates/builds/buildsrc-usage/buildSrc/src/main/kotlin/Usage.kt
kover-gradle-plugin/src/functionalTest/templates/builds/buildsrc-usage/requires
kover-gradle-plugin/src/functionalTest/templates/builds/buildsrc-usage/settings.gradle.kts
kover-gradle-plugin/src/functionalTest/templates/builds/buildsrc-usage/src/main/kotlin/ExampleClass.kt
kover-gradle-plugin/src/functionalTest/templates/builds/buildsrc-usage/src/test/kotlin/TestClass.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/reports/ReportsVariantApplier.kt

Fixes #415
`kotlin-dsl` itself specifies the language version to ensure compatibility of the Kotlin DSL API. 
Since we ourselves guarantee and test compatibility with previous Gradle versions, we can override language version.
The easiest way to do this now is to specify the version in the `afterEvaluate` block

Fixed usage Kover Gradle Plugin in buildSrc directory

---

docs/gradle-plugin/configuring.md
docs/gradle-plugin/index.md
kover-gradle-plugin/api/kover-gradle-plugin.api
kover-gradle-plugin/examples/jvm/defaults/build.gradle.kts
kover-gradle-plugin/examples/jvm/merged/build.gradle.kts
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ReportAnnotationFilterTests.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ReportsFilteringTests.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/TasksOrderingTests.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/VerificationTests.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/writer/KoverReportWriter.kt
kover-gradle-plugin/src/functionalTest/templates/builds/no-tests-jvm/build.gradle.kts
kover-gradle-plugin/src/functionalTest/templates/builds/no-tests-mpp/build.gradle.kts
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/AppliersCommons.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/ProjectApplier.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/reports/ReportsVariantApplier.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverReportExtension.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/internal/KoverReportExtension.kt

Now it is not necessary to specify the same rules in different report variants, it is enough to specify them at the root, and they will be inherited in each variant, if they are not explicitly overridden.

Added ability to specify verification rules in the root of reports config

---

kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/KoverHtmlTask.kt

Fixes HTML report paths not being clickable
Closes #470

Update HTML report path to be clickable

---

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/BuildCacheRelocationTests.kt

To display the build log, there is a need to catch an exception and add an output to the message.

Fixing logging errors in the `BuildCacheRelocationTests` test

---

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ReportsCachingTests.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ReportsUpToDateTests.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/checker/Checker.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/checker/CheckerTypes.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/configurator/BuildConfigurator.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/configurator/ConfiguratorTypes.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/runner/StepsRunner.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/JvmTestTaskConfigurator.kt

If the build cache is not used and the build directory is not cleared before the test run, then the coverage data from previous test runs are merged with the data from the recent run. In this case, the report may include coverage from those tests that were removed in the latest version of the code.
To solve this, it is necessary to delete the binary report file before each run of the test task.
Fixes #489

Fixed adding data to an already existing binary report file

---

.gitignore
kover-gradle-plugin/build.gradle.kts

For context: https://github.com/Kotlin/kotlinx.coroutines/issues/3929 and https://github.com/Kotlin/kotlinx.coroutines/pull/3960
BTW, is there a reason why `kover` API reference is not published under `https://kotlinlang.org/docs/home.html` API reference section?

Update Gradle Dokka configuration to make sure "source" button is visible in all API docs

---

kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/JvmTestTaskConfigurator.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/jacoco/JacocoOnlineInstrumentation.kt

It seems that after Robolectric instrumentation, source locations are lost and JaCoCo does not instrument such classes by default. There is a need to change the flag to disable this behavior.
After changing this flag, errors occur in the instrumentation of JVM classes (because they were previously excluded due to the lack of sources). The package with these classes was determined empirically.
Fixes #530

Fixed the presence of classes instrumented with Robolectric in Jacoco reports

---

gradle/libs.versions.toml
kover-cli/src/main/kotlin/kotlinx/kover/cli/commands/ReportCommand.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverVersions.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/kover/KoverHtmlOrXmlReport.kt

When generating an HTML report, errors sometimes occur when reading the freemarker template from resources. The exact cause of the error has not yet been determined (relates to the Gradle isolated class loaders), but it disappears when you try to read again. In some cases, it is necessary to increase the number of repetitions, so this setting was made in Kover Gradle plugin.
Fixes #510

Fixed `Stream closed` error  when generating Kover HTML report

---

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ReportsFilteringTests.kt
kover-gradle-plugin/src/functionalTest/templates/sources/different-packages/main/kotlin/FooSources.kt
kover-gradle-plugin/src/functionalTest/templates/sources/different-packages/main/kotlin/Sources.kt
kover-gradle-plugin/src/functionalTest/templates/sources/different-packages/test/kotlin/TestClass.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tools/jacoco/JacocoAnt.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/util/Util.kt

Class filtering in JaCoCo took place by file name. Because previously the absolute path to the class file was taken, the filter worked on any occurrence of the specified string, even if it was no match starting from the root package.
Now the search takes place relative to the classes root directory, which allows you to change the regular expression of the search, and remove arbitrary characters at the beginning in it.
Fixes #543

Fixed package exclusion in reports for JaCoCo

---

README.md

Prior to this, the documentation did not explicitly specify that the plugin changes the behavior of tests even when Kover tasks are not called.
Resolves #531

Added explanations about apply of the plugin

---

kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/locators/ProvidedVariantsLocator.kt

In older versions of AGP (lower than 7.0), the `androidComponents` project extension did not exist and this is the expected situation. However, in the current implementation, in the absence of this extension, the KoverCriticalException error was thrown.
In this case, it is necessary not to throw an error, but execute fallback branch
Fixes #520

Fixed error: Kover requires extension with name 'androidComponents'

---

kover-gradle-plugin/api/kover-gradle-plugin.api
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/KoverMerge.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverVariantConfig.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/internal/VariantsImpl.kt

Previous versions of the functions had vararg parameters, this is not always convenient if the List is presented when or Groovy is used.
Relates #570

Added overload for functions of KoverVariantCreateConfig

---

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/LoggingTaskTests.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/services/KoverPrintLogTask.kt

At the moment, the coverage was printed with the `lifecycle` level. However, if user limit the logs to the `--warn` level, the coverage stops printing. 
Now coverage is printed with the quite level, thanks to this it is printed even with the limitations of `--warn` and `--quiet`.
Fixes #557

Changed log level for print coverage task

---

kover-gradle-plugin/api/kover-gradle-plugin.api
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/TaskInterfacesTests.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/tasks/KoverTasks.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/KoverHtmlTask.kt

if there is a need to analyze the HTML report after it is generated, or if you need to improve the report (for example, by editing CSS styles), you need to know the directory of each report. Currently, it is not possible to easily link a specific report generation task and a directory.
Resolves #590

Expose reportDir property in KoverHtmlReport interface

---

kover-gradle-plugin/api/kover-gradle-plugin.api
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/TaskInterfacesTests.kt
kover-gradle-plugin/src/functionalTest/templates/builds/android-test-tasks-filtering/app/build.gradle.kts
kover-gradle-plugin/src/functionalTest/templates/builds/android-test-tasks-filtering/app/src/main/AndroidManifest.xml
kover-gradle-plugin/src/functionalTest/templates/builds/android-test-tasks-filtering/app/src/main/java/kotlinx/kover/test/android/DebugUtil.kt
kover-gradle-plugin/src/functionalTest/templates/builds/android-test-tasks-filtering/app/src/main/java/kotlinx/kover/test/android/MainActivity.kt
kover-gradle-plugin/src/functionalTest/templates/builds/android-test-tasks-filtering/app/src/main/java/kotlinx/kover/test/android/Maths.kt
kover-gradle-plugin/src/functionalTest/templates/builds/android-test-tasks-filtering/app/src/main/res/layout/activity_main.xml
kover-gradle-plugin/src/functionalTest/templates/builds/android-test-tasks-filtering/app/src/main/res/values/colors.xml
kover-gradle-plugin/src/functionalTest/templates/builds/android-test-tasks-filtering/app/src/main/res/values/strings.xml
kover-gradle-plugin/src/functionalTest/templates/builds/android-test-tasks-filtering/app/src/main/res/values/themes.xml
kover-gradle-plugin/src/functionalTest/templates/builds/android-test-tasks-filtering/app/src/test/java/kotlinx/kover/test/android/LocalTests.kt
kover-gradle-plugin/src/functionalTest/templates/builds/android-test-tasks-filtering/build.gradle.kts
kover-gradle-plugin/src/functionalTest/templates/builds/android-test-tasks-filtering/gradle.properties
kover-gradle-plugin/src/functionalTest/templates/builds/android-test-tasks-filtering/settings.gradle.kts
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/tasks/VariantReportsSet.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/tasks/KoverTasks.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/AbstractKoverReportTask.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/KoverBinaryTask.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/KoverDoVerifyTask.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/KoverFormatCoverageTask.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/KoverHtmlTask.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/KoverVerifyTask.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/KoverXmlTask.kt

Property `variantName` will help to filter Kover tasks by selecting those that relate to specific variant.
Resolves #587

Added property variantName to KoverReport interface

---

README.md

* It is here to stay
* We would live to maintain it in its current form and have a clear vision for future development (#608) with a straightforward migration plan

Promote status of the Kover to Beta

---

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/FinalizingEnqueueTests.kt
kover-gradle-plugin/src/functionalTest/templates/builds/android-subproject-apply/app/build.gradle.kts
kover-gradle-plugin/src/functionalTest/templates/builds/android-subproject-apply/app/src/main/AndroidManifest.xml
kover-gradle-plugin/src/functionalTest/templates/builds/android-subproject-apply/app/src/main/java/kotlinx/kover/test/android/DebugUtil.kt
kover-gradle-plugin/src/functionalTest/templates/builds/android-subproject-apply/app/src/main/java/kotlinx/kover/test/android/MainActivity.kt
kover-gradle-plugin/src/functionalTest/templates/builds/android-subproject-apply/app/src/main/java/kotlinx/kover/test/android/Maths.kt
kover-gradle-plugin/src/functionalTest/templates/builds/android-subproject-apply/app/src/main/res/layout/activity_main.xml
kover-gradle-plugin/src/functionalTest/templates/builds/android-subproject-apply/app/src/main/res/values/colors.xml
kover-gradle-plugin/src/functionalTest/templates/builds/android-subproject-apply/app/src/main/res/values/strings.xml
kover-gradle-plugin/src/functionalTest/templates/builds/android-subproject-apply/app/src/main/res/values/themes.xml
kover-gradle-plugin/src/functionalTest/templates/builds/android-subproject-apply/app/src/test/java/kotlinx/kover/test/android/LocalTests.kt
kover-gradle-plugin/src/functionalTest/templates/builds/android-subproject-apply/build.gradle.kts
kover-gradle-plugin/src/functionalTest/templates/builds/android-subproject-apply/gradle.properties
kover-gradle-plugin/src/functionalTest/templates/builds/android-subproject-apply/settings.gradle.kts
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/locators/ProvidedVariantsLocator.kt

Fixed enqueue for Android projects

---

kover-gradle-plugin/api/kover-gradle-plugin.api
kover-gradle-plugin/examples/android/multiproject/app/build.gradle.kts
kover-gradle-plugin/examples/android/variantUsage/app/build.gradle.kts
kover-gradle-plugin/examples/jvm/merged/build.gradle.kts
kover-gradle-plugin/examples/jvm/single-kmp/build.gradle.kts
kover-gradle-plugin/examples/jvm/single/build.gradle.kts
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/MergingTests.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ReportAnnotationFilterTests.kt
kover-gradle-plugin/src/functionalTest/templates/builds/sourcesets-mpp/build.gradle.kts
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/FinalizeKover.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/KoverMerge.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/artifacts/AbstractVariantArtifacts.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/tasks/VariantReportsSet.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverProjectExtension.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverReportsConfig.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverVariantConfig.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/internal/KoverProjectExtensionImpl.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/internal/MergeImpl.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/internal/ReportsImpl.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/internal/VariantsImpl.kt

The new DSL will allow to write chains like `kover.reports.total { ... }` instead of `kover { reports { total { ... } } }`.
However, the DomainObjectContainer for variants has not been implemented, because it will be necessary to rework the workflow with different types of variants, which is part of a larger reworking of the DSL.
Resolves #600

Partially apply recommendations for improving DSL

---

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ArtifactGenerationTests.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/services/KoverArtifactGenerationTask.kt

Fixes https://github.com/Kotlin/kotlinx-kover/issues/633

Fix issue with identical cache keys between projects

---

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/BuildCacheRelocationTests.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/services/KoverArtifactGenerationTask.kt

Fixes https://github.com/Kotlin/kotlinx-kover/issues/633
Alternative solution to https://github.com/Kotlin/kotlinx-kover/pull/636
Caching should only be enabled for tasks that do heavy computations and this task does not do so.
Potentially it would be good to merge both PRs, even if caching is disabled, we should make sure that data that is used to produce an output is declared as an import.

Disable caching on kover artifact tasks

---

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/ConfigurationCacheTests.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/PrepareKover.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/tasks/VariantReportsSet.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/reports/AbstractKoverReportTask.kt

Due to the fact that a file was used as task input, it was placed in the configuration cache as entry, and changing this file causes the cache invalidation.
Problem in line `localArtifact.set(variant.artifactGenTask.flatMap { task -> task.artifactFile })`. flatMap function behaves strangely enough with the configuration cache, see also https://github.com/gradle/gradle/issues/25645
Fixes #646

Fixed reusing of configuration cache

---

kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/commons/names/PluginId.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/project/KoverProjectGradlePlugin.kt

The types are different but they look the same through `DynamicBean`.

Include Android compilations in aggregation

---

kover-jvm-agent/src/main/java/kotlinx/kover/jvmagent/KoverJvmAgentPremain.java

By mistake, even the `include` arguments read like `exclude`

Fixed JVM agent arguments parsing

---

kover-maven-plugin/docs/index.md

Spotted when setting up the plugin from the [docs](https://kotlin.github.io/kotlinx-kover/maven-plugin/).
`filters` shouldn't have another child block called `filters`.
Examples are already correct [here](https://github.com/Kotlin/kotlinx-kover/blob/main/kover-maven-plugin/examples/filters-common/pom.xml#L101) and [here](https://github.com/Kotlin/kotlinx-kover/blob/main/kover-maven-plugin/examples/filters-rules/pom.xml#L120).

Maven plugin - correction to documentation of filters

---

kover-maven-plugin/src/functionalTest/kotlin/kotlinx/kover/maven/plugin/tests/functional/cases/MavenPluginTests.kt
kover-maven-plugin/src/functionalTest/kotlin/kotlinx/kover/maven/plugin/tests/functional/framework/Checker.kt
kover-maven-plugin/src/functionalTest/templates/tests/kotlin-empty-config/pom.xml
kover-maven-plugin/src/functionalTest/templates/tests/kotlin-empty-config/src/main/kotlin/Main.kt
kover-maven-plugin/src/functionalTest/templates/tests/kotlin-empty-config/src/test/kotlin/MainKtTest.kt
kover-maven-plugin/src/main/kotlin/kotlinx/kover/maven/plugin/mojo/abstracts/AbstractCoverageTaskMojo.kt

When a configuration is specified in the execution for the `compile` target, but the `sourceDirs` child element is missing, an error occurred. A check has been added to fix the error.
Fixes #701

Fixed warning for empty Kotlin plugin configuration

---

kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/CompatibilityTests.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/aggregation/settings/KoverSettingsGradlePlugin.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/PrepareKover.kt

`attributes` block shouldn't be used in dependency configurations
Fixes #716

Fixed Gradle 9.0 migration issue

---

kover-gradle-plugin/api/kover-gradle-plugin.api
kover-gradle-plugin/docs/index.md
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/SourceSetsTests.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/checker/Checker.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/checker/CheckerTypes.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/runner/BuildsRunner.kt
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/framework/starter/Commons.kt
kover-gradle-plugin/src/functionalTest/templates/builds/sourcesets-multi/build.gradle.kts
kover-gradle-plugin/src/functionalTest/templates/builds/sourcesets-multi/settings.gradle.kts
kover-gradle-plugin/src/functionalTest/templates/builds/sourcesets-multi/src/extra/kotlin/ExtraClass.kt
kover-gradle-plugin/src/functionalTest/templates/builds/sourcesets-multi/src/foo/kotlin/FooClass.kt
kover-gradle-plugin/src/functionalTest/templates/builds/sourcesets-multi/src/main/kotlin/MainClass.kt
kover-gradle-plugin/src/functionalTest/templates/builds/sourcesets-multi/src/test/kotlin/TestClasses.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/KoverMerge.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/appliers/artifacts/JvmVariantArtifacts.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/KoverVariantConfig.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/dsl/internal/VariantsImpl.kt

Added ability to specify inclusion filter for source sets

---

kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/tasks/services/KoverAgentJarTask.kt

There are two cases where this task works:
- for the Kover tool it just copies the jar file from dependencies to the build directory
- for the JaCoCo tool it unzips the file from dependency and copies its content to the build directory
For both these cases using build cache is uneffective, since local copying and uzipping are fast itself. But using build cache inflates it, and it runs slower because the build cache performs some number of additional calculations and archiving.
Fixes #748

Disabled caching for KoverAgentJarTask

---

gradle/wrapper/gradle-wrapper.properties
kover-cli/build.gradle.kts
kover-gradle-plugin/src/functionalTest/kotlin/kotlinx/kover/gradle/plugin/test/functional/cases/AndroidKmpLibTests.kt
kover-gradle-plugin/src/functionalTest/templates/builds/android-kmp-library/build.gradle.kts
kover-gradle-plugin/src/functionalTest/templates/builds/android-kmp-library/settings.gradle.kts
kover-gradle-plugin/src/functionalTest/templates/builds/android-kmp-library/src/androidMain/kotlin/AndroidClass.kt
kover-gradle-plugin/src/functionalTest/templates/builds/android-kmp-library/src/commonMain/kotlin/ExampleClass.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/locators/KotlinMultiPlatformLocator.kt
kover-gradle-plugin/src/main/kotlin/kotlinx/kover/gradle/plugin/util/DynamicBean.kt

`com.android.kotlin.multiplatform.library` Gradle plugin was recently added. Support for a new type of compilations has been added: `com.android.build.api.variant.impl.KotlinMultiplatformAndroidLibraryTargetImpl`.
Due to the limitations of the Gradle API, it has not yet been possible to implement a reliable way to get javac details for this plugin.
Also, the Gradle version is upgraded to `8.13`.
Fixes #747

Added support for KMP Android library plugin
